extends Node

# GODOT_4 - can't use load on these png images, switched to load, had to remove const from  ITEMS

var ITEMS = {
	'arrows'  : {
		'count'             : 5,
		'description' 		: 'a stack of basic arrows',
		'equipable'         : true,
		'inventory-texture' : preload('res://assets/images/scenes/Arrows/arrows-inventory.png'),
		'name'              : 'Arrows',
		'stackable' 		: true,
		'scene'             : null,
	},
	'bow-wooden'  : {
		'count'             : 1,
		'description' 		: 'a shoddy wooden bow',
		'equipable'         : true,
		'inventory-texture' : preload('res://assets/items/bow-wooden-inventory.png'),
		'name'              : 'Wooden Bow',
		'stackable' 		: false,
		'scene'             : 'res://scenes/Weapons/Bow/bow.tscn'
	},
	'firewood' : {
		'count'             : 1,
		'description' 		: 'Burn wood; cook stuff',
		'equipable'         : false,
		'inventory-texture'	: preload('res://assets/images/scenes/Firewood/firewood-inventory.png'),
		'name'              : 'Firewood',
		'stackable' 		: true,
	},
	'charcoal'  : {
		'description' 		: "A greasy lump of coal.\nCan be used to\nmake torches.",
		'drop-image'        : 'res://assets/images/items/charcoal-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/images/items/charcoal-inventory.png'),
		'name'              : 'Charcoal',
		'stackable' 		: true,
	},
	'lavender'  : {
		'description' 		: "A purple flower.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/lavender-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load("res://assets/lavender-inv.png"),
		'name'              : 'Lavender',
		'stackable' 		: true,
	},
	'tiger-lily'  : {
		'description' 		: "A tiger lily.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/tiger-lily-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/tiger-lily-inv.png'),
		'name'              : 'Tiger Lily',
		'stackable' 		: true,
	},
	'delphinium'  : {
		'description' 		: "A delphinium.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/delphinium-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/delphinium-inv.png'),
		'name'              : 'Delphinium',
		'stackable' 		: true,
	},
	'fly-agaric'  : {
		'description' 		: "A fly agaric.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/fly-agaric-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/fly-agaric-inv.png'),
		'name'              : 'Fly Agaric',
		'stackable' 		: true,
	},
	'mint-leaf'  : {
		'description' 		: "A mint leaf.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/mint-leaf-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/mint-leaf-inv.png'),
		'name'              : 'Mint Leaf',
		'stackable' 		: true,
	},
	'currant'  : {
		'description' 		: "A currant.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/currant-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/currant-inv.png'),
		'name'              : 'Currant',
		'stackable' 		: true,
	},
	'romaine'  : {
		'description' 		: "A piece of romain lettuce.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/romaine-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/romaine-inv.png'),
		'name'              : 'Romaine',
		'stackable' 		: true,
	},
	'wheat'  : {
		'description' 		: "A piece of wheat.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/wheat-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/wheat-inv.png'),
		'name'              : 'Wheat',
		'stackable' 		: true,
	},
	'dead-frog'  : {
		'description' 		: "A dead frog.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/dead-frog-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/dead-frog-inv.png'),
		'name'              : 'Dead Frog',
		'stackable' 		: true,
	},
	'persons-hand'  : {
		'description' 		: "A man's hand.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/persons-hand-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/person-hand-inv.png'),
		'name'              : "Man's Hand",
		'stackable' 		: true,
	},
	'dead-hair'  : {
		'description' 		: "A few strands of dead hair.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/dead-hair-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/dead-hair-inv.png'),
		'name'              : 'Dead Hair',
		'stackable' 		: true,
	},
	'blueberry'  : {
		'description' 		: "A blueberry.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/blueberry-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/blueberry-inv.png'),
		'name'              : 'Blueberry',
		'stackable' 		: true,
	},
	'rock-grains'  : {
		'description' 		: "Some stone grains.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/stone-grains-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/stone-grains-inv.png'),
		'name'              : 'Stone Grains',
		'stackable' 		: true,
	},
	'newt-eye'  : {
		'description' 		: "An eye of newt.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/newt-eye-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/newt-eye-inv.png'),
		'name'              : 'Eye of Newt',
		'stackable' 		: true,
	},
	'coconut'  : {
		'description' 		: "A coconut.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/coconut-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/coconut-inv.png'),
		'name'              : 'Coconut',
		'stackable' 		: true,
	},
	'dead-mouse'  : {
		'description' 		: "A dead mouse.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/dead-mouse-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/dead-mouse-inv.png'),
		'name'              : 'Dead Mouse',
		'stackable' 		: true,
	},
	'donut-lasso'  : {
		'description' 		: "A donut lasso.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/donut-lasso-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/donut-lasso-inv.png'),
		'name'              : 'Donut Lasso',
		'stackable' 		: true,
	},
	'bananas'  : {
		'description' 		: "Two bananas.\nCan be used to\nbrew potions.",
		'drop-image'        : 'res://assets/bananas-drop.png',
		'equipable'         : false,
		'inventory-texture'	: load('res://assets/bananas-inv.png'),
		'name'              : 'Bananas',
		'stackable' 		: true,
	}
}
